### ISSUE TITLE
Question on how to compile the files

### ISSUE THREAD

**Issue by Lukeeeeee** [tanz0119/thesis#1]
Hi, thanks for sharing. May I know which command to compile the file? pdflatex, latex or others? for bibliography, use biber or bibtex? 

Thanks.

**Comment by tanz0119** [comment]
Hi, I am using TeXnicCenter to compile the file using latex. For the bibliography, I am using bibtex.
You may also refer to this guide for more information https://sites.google.com/site/jrlhost/links/latex

**Comment by Lukeeeeee** [comment]
many thanks.
